### ISSUE TITLE
GetDocumentsFolder error: The system cannot find the path specified

### ISSUE THREAD

**Issue by zavatar** [arduino/go-win32-utils#1]
Windows 7 system.
This error comes from arduino-cli. "Error creating default configuration: getting default sketchbook dir: getting Documents path: The system cannot find the path specified."

**Comment by cmaglie** [comment]
@zavatar 
Sorry, this is a secondary repository so this issue went into the woods...

I hope that in the meantime the issue has been solved in some way.
Otherwise, I'd recommend opening an issue directly in the arduino-cli repository that will surely have better support and more eyes looking at it. We can eventually escalate the issue here if needed.
